### ISSUE TITLE
Auth Email From Correct Event

### ISSUE THREAD

**Issue by kwakr** [Pinjasaur/whenisgucci#123]
When you receive an auth email, it should link you to the event in which the auth email was generated from.

i.e. I create an event and never authorize my email. Months later, I then create a new event and click on my new auth link.

*Currently* I will be brought to the first event in which I needed to auth my email for.
*Expected behavior* will be being brought to the event that generated that auth email.

**Comment by Pinjasaur** [comment]
For implementing, adding the hashed event ID to the auth URL and then parsing that in the `/auth` route. If no hashed event ID is provided (to provide backwards compatibility) then redirect to the most recently created event.
