### ISSUE TITLE
Add created/updated to Mongo Models

### ISSUE THREAD

**Issue by Pinjasaur** [Pinjasaur/whenisgucci#132]
Add `timestamps: true` to each Mongoose Schema.

Docs: https://mongoosejs.com/docs/guide.html#timestamps

**Comment by theashraf** [comment]
Can I work on this?

**Comment by Pinjasaur** [comment]
Hey @theashraf, you're more than welcome to work on this. It _should_ be a very straightforward code update.

There's a short document outlining basic contributing guidelines: https://github.com/Pinjasaur/whenisgucci/blob/2d08f8cace68539c7e568d2e8936cae83b01a11f/CONTRIBUTING.md
