### ISSUE TITLE
Rename `test/` to `tests/`

### ISSUE THREAD

**Issue by Pinjasaur** [Pinjasaur/whenisgucci#134]
In Rapid Development Haste:tm:, failed to find the docs for Mocha that allows you to override where test files are expected to reside. Would prefer to use `tests/` to keep all the directories consistent from the current (default) `test/`.

Docs: https://mochajs.org/#the-test-directory

**Comment by Leos1113** [comment]
Done! https://github.com/Pinjasaur/whenisgucci/pull/135

**Comment by Pinjasaur** [comment]
Closed in #135. 🚀
