### ISSUE TITLE
Create API endpoint creating event

### ISSUE THREAD

**Issue by kwakr** [Pinjasaur/whenisgucci#20]
Create an API endpoint for the POST call to create an event

**Comment by Pinjasaur** [comment]
Something like `/api/event/create` that takes the creator email, checks if there's already a creator, and then creates the event.

**Comment by Pinjasaur** [comment]
- http://thecodebarbarian.com/80-20-guide-to-async-await-in-node.js.html
- http://mongoosejs.com/docs/promises.html
- https://medium.com/@zurfyx/building-a-scalable-node-js-express-app-1be1a7134cfd
- https://codeburst.io/using-mongoose-validation-with-async-await-c3a9255459e1
