### ISSUE TITLE
"Copy Event Link" Doesn't Work

### ISSUE THREAD

**Issue by Pinjasaur** [Pinjasaur/whenisgucci#79]
The "Copy Event Link" on an `/results` page doesn't work.

See below:

![image](https://user-images.githubusercontent.com/6335792/38956528-d6526dee-4325-11e8-8040-49e0172047de.png)

**Comment by Pinjasaur** [comment]
Also needs to have form controls elements styled w/ Bulma. (In the same way as the Create page).

**Comment by kwakr** [comment]
fixaroo-ed
