### ISSUE TITLE
"Send Response" Needs Styling & Show Summary

### ISSUE THREAD

**Issue by Pinjasaur** [Pinjasaur/whenisgucci#80]
"Send Response" modal on an `/respond` page needs to:

- form controls styled with Bulma (see Create page)
- display the "Time Summary" or remove that section
- remove the copy regarding a confirmation email upon success

![image](https://user-images.githubusercontent.com/6335792/38956916-0ab292b6-4327-11e8-972c-9b7e8ec53990.png)

![image](https://user-images.githubusercontent.com/6335792/38956988-3f0620e6-4327-11e8-8689-f8b9bafce94f.png)

**Comment by kwakr** [comment]
blam - pow - bam!
Killin all the issues today
